### ISSUE TITLE
Crashing on launch due to minidump?

### ISSUE THREAD

**Issue by ZaneH** [timfish/sentry-tauri#1]
Hello,

I have put up a branch of the code I'm using (with sentry-tauri) here: https://github.com/ZaneH/piano-trainer/tree/sentry-dev

I've got it setup like the example and I am receiving events however it crashes on launch due to:

![image](https://user-images.githubusercontent.com/8400251/178129145-3ccf4b38-3806-40a8-b56c-01303de1e66b.png)

I checked to make sure my firewalls aren't blocking anything & that there isn't a stray background process. It worked for a little bit and then stopped. Thanks!

**Comment by timfish** [comment]
Thanks for opening an issue, I'll take a look!

I'm guessing this is macOS?

**Comment by ZaneH** [comment]
Thanks! Yes, I'm running macOS Monterey 12.2.1

**Comment by timfish** [comment]
When running `yarn tauri dev`, the app keeps rebuilding and then restarting and this causes the server port to already be in use and an `expect` panics. I've now removed all sources of panics from `sentry-rust-minidump` and published v0.1.1. If you delete your lock file you should get this update.

When I run a production build of the app it doesn't panic and I don't get the restarting so I'm guessing the restarting is due to the dev mode?

**Comment by ZaneH** [comment]
The Tauri Discord helped me get past the restart loops

If anyone has the same issue, you'll need the `TAURI_DEV_WATCHER_IGNORE_FILE` set to a the path of your `.taurignore` file. I added:
```
*
```
to `.taurignore` which will exclude all files in the directory from being watched for changes.
